# Generated by Django 3.2.9 on 2021-11-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='phone',
            field=models.TextField(default='(+234) 9061341499'),
        ),
    ]
