# Generated by Django 3.2.9 on 2021-11-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_aboutme_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
