# Generated by Django 3.2.9 on 2021-11-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_aboutme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='resume',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
