# Generated by Django 3.2.9 on 2021-11-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='bg_photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
