# Generated by Django 3.2.9 on 2021-11-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_aboutme_bg_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='project_bg',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
