# Generated by Django 3.2.9 on 2021-11-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_aboutme_project_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='title')),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('work_done', models.TextField(blank=True)),
            ],
        ),
    ]
