# Generated by Django 3.2.9 on 2021-11-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_projectspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='customers',
            field=models.IntegerField(blank=True, default='1'),
        ),
    ]
